services:

  backend:
    image: abhishek2704/unirent-backend:latest
    container_name: unirent-backend
    restart: unless-stopped

    env_file:
      - ./Backend/.env

    environment:
      NODE_ENV: production
      PORT: 5000

    volumes:
      - backend_uploads:/app/uploads

    ports:
      - "127.0.0.1:5000:5000"

  frontend:
    image: abhishek2704/unirent-frontend:latest
    container_name: unirent-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3001:80"

volumes:
  backend_uploads:
